1. What is the total revenue generated by male vs. female customers?
Select "gender", SUM("purchase_amount") as revenue
from customer
group by "gender";


2.Which customers used a discount but still spent more than the average purchase amount?
Select "customer_id","purchase_amount"
from customer
where "discount_applied"='Yes' and "purchase_amount">=(select AVG("purchase_amount") From customer)


3.Which are the top 5 products with the highest average review rating?
Select "item_purchased", Round(AVG("review_rating"::numeric),2) as "Average Product Rating"
From customer
group by "item_purchased"
order by AVG("review_rating") desc
limit 5;


4.Compare the average purchase amounts between Standard and Express shipping.
Select "shipping_type",
Round(AVG("purchase_amount"),2)
from customer
where "shipping_type" IN ('Standard','Express')
group by "shipping_type"



5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select "subscription_status",
Count("customer_id") as "Total Customers",
Round(AVG("purchase_amount"),2) as "Average Spend",
Round(Sum("purchase_amount"),2) as "Total Revenue"
from customer
group by "subscription_status"
order by "Total Revenue","Average Spend" desc;



6.Which 5 products have the highest percentage of purchases with discounts applied?
Select "item_purchased",
Round(Sum(100 * CASE WHEN "discount_applied" = 'Yes' THEN 1 ELSE 0 END)/Count(*),2) as "Discount Rate"
from customer
group by "item_purchased"
order by "Discount Rate" desc
limit 5;



7.Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with "Customer type" as(
Select "customer_id","previous_purchases",
CASE
WHEN "previous_purchases" = 1 THEN 'NEW'
WHEN "previous_purchases" BETWEEN 2 AND 10 THEN 'Returning'
ElSE 'Loyal'
END AS "Customer Segment"
from customer
)
Select "Customer Segment", Count(*) AS "Number Of Customer"
from "Customer type"
group by "Customer Segment"




8.What are the top 3 most purchased products within each category?
with "Item counts" AS (
select "category",
"item_purchased",Count("customer_id") AS "Total orders",
ROW_NUMBER() OVER( partition by "category" order by count("customer_id") Desc) AS "Item rank"
from customer
group by "category","item_purchased"
)
select "Item rank","category","item_purchased","Total orders"
from "Item counts"
where "Item rank"<=3;




9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select "subscription_status",
Count("customer_id") AS "Repeat Buyers"
from customer
where "previous_purchases">5
group by "subscription_status"




10.What is the revenue contribution of each age group?
Select "age_group",
SUM("purchase_amount") AS "Total Revenue"
from customer
group by "age_group"
order by "Total Revenue" desc;